### ISSUE TITLE
Add benchamark

### ISSUE THREAD

**Issue by ai** [antiflasher/apcach#8]
The best way to write a benchmark is to use library.

```sh
pnpm add --save-dev benchmark
```

Then you can copy benchmark code from https://github.com/ai/nanoevents/blob/main/test/benchmark.js to `benchmark.js`

To run it you need to call `node ./benchmark.js`

Don’t forget to add `benchmark.js` to `.npmignore`.

**Comment by antiflasher** [comment]
Added
